import { useState } from 'react'
import TextField from '../../components/TextField'
import Button from '../../components/Button'
import { useNavigate } from 'react-router-dom'
import { useDispatch } from 'react-redux'
import { addUser } from './userSlice'
import { v4 as uuidv4 } from 'uuid'

const AddUser = () => {
    // Import the "useNavigate" hook to enable programmatic navigation.
    const navigate = useNavigate();

    // Get access to the Redux "dispatch" function using the "useDispatch" hook.
    const dispatch = useDispatch();

    // Create a state variable "values" to manage user input for name and email fields.
    const [values, setValues] = useState({ name: '', email: '' });

    // Define a function "handleAddUser" to dispatch an "addUser" action with a new user object,
    // reset the input fields, and navigate to the home page ('/').
    const handleAddUser = () => {
        // Dispatch an "addUser" action with a new user object containing an ID generated by "uuidv4",
        // and the name and email values from the "values" state.
        dispatch(addUser({ id: uuidv4(), name: values.name, email: values.email }));

        // Reset the input fields by setting "values" to an empty object.
        setValues({ name: '', email: '' });

        // Use the "navigate" function to navigate to the home page ('/').
        navigate('/');
    }

    return (
        <div className='mt-10 max-w-xl mx-auto '>
            {/* Render a text input field for the "Name" with value and onChange handlers */}
            <TextField
                label='Name'
                value={values.name}
                onChange={(e) => setValues({ ...values, name: e.target.value })}
                inputProps={{ type: 'text', placeholder: 'John Doe' }}
            />
            <br />
            {/* Render a text input field for the "Email" with value and onChange handlers */}
            <TextField
                label='Email'
                value={values.email}
                onChange={(e) => setValues({ ...values, email: e.target.value })}
                inputProps={{ type: 'email', placeholder: 'johndoe@gmail.com' }}
            />
            {/* Render a "Submit" button with an onClick handler */}
            <Button onClick={handleAddUser}>Submit</Button>
        </div>

    )
}

export default AddUser
